site_name: 数据采集从入门到放弃
nav:
    - 介绍: index.md
    - 目录: content.md
    - 第一章:爬虫介绍: 
      - 爬虫介绍: introduce_spider/introduce_spider.md
      - 爬虫面试: introduce_spider/spider_interview.md
    - 第二章：HTTP协议介绍: 
      - HTTP协议: network/HTTP.md
      - TCP协议: network/TCP.md
      - 实战：模拟登陆: network/session.md
    - 第三章：Requests使用:
      - Requests基础使用: requests/basic_useage.md
      - Requests源码分析: requests/request_source_code.md
      - 注意事项: requests/request_attention.md
    - 第四章：Xpath介绍:
      - lxml使用: xpath/lxml.md
      - scrapy的selector: xpath/scrapy_selector.md
      - 注意事项: xpath/attention.md
    - 第五章：MongoDB与MySQL:
      - MongoDB使用: database/MongoDB.md
      - MySQL使用: database/MySQL.md
      - 注意事项: database/attention.md


theme: readthedocs

